name: Build test image

on:
  workflow_dispatch:

jobs:
  ci-cd-image:
    uses: ./.github/workflows/image-tmp.yml
    with:
      region: "us-east-2"
      repo: "enigma_backend"
      deploy_env: "test"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
