name: ci run

on:
  workflow_call:
    inputs:
      codeCoverage:
        required: true
        type: string
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: "test_coverage"
        uses: docker://camistyles/test-node-ci:node-test
        env:
          CI_COVERAGE_MIN: "70"
        with:
          args: test.sh

