name: ci run

on:
  workflow_call:
    inputs:
      codeCoverage:
        required: true
        type: string
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    container:
      image: camistyles/test-node-ci:node-test
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "test_coverage"
        run: "test.sh"

