name: ci run

on:
  workflow_call:
    inputs:
      codeCoverage:
        required: true
        type: string
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "test_coverage"
        uses: docker://camistyles/test-node-ci:node-test
        with:
          args: test.sh

