name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  ci_other_file:
    uses: camilo-rojas/infra_test/.github/workflows/node.yml@master
    with:
      codeCoverage: "50"
