name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  ci-other-file:
    uses: ./.github/workflows/build-node.yml
    # with:
    #   codeCoverage: ${{ secrets.CI_COVERAGE_MIN }}
