name: Deploy production env

on: 
  push:
    branches:
      - "master----"
  
jobs:
  ci:
    uses: ./.github/workflows/build-node.yml
    with:
      codeCoverage: "50"
  
  ci-cd-image:
    uses: ./.github/workflows/image-tmp.yml
    needs: ci
    with:
      region: "us-east-2"
      repo: "enigma_backend"
      deploy_env: "production"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    uses: ./.github/workflows/deploy-tmp.yml
    needs:
      - ci
      - ci-cd-image
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      image: ${{ needs.ci-cd-image.outputs.built-image }}
      task-definition: backend-ecs-task-v2-prodV2
      container-name: backend-container-v2-prodV2
      app-service: backend-ecs-service-v2-prodV2
      app-cluster: marketplace-ecs-cluster-prod
      deploy_env: production
