name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  ci-other-file:
    uses: ./.github/workflows/reutil/build-node.yml
    with:
      codeCoverage: "50"
