name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  ci-other-file:
    uses: camilo-rojas/node_test/.github/workflows/build-node.yml@master
    with:
      codeCoverage: "50"
