name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
  
jobs:
  ci:
    uses: ./.github/workflows/build-node.yml
    with:
      codeCoverage: "50"
      region: "us-east-2"
      repo: "enigma_backend"
      deploy_env: "test"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    uses: ./.github/workflows/deploy-tmp.yml
    needs: ci
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      image: ${{ needs.ci.outputs.built-image }}
      task-definition: backend-ecs-task-v2-testV2
      container-name: backend-container-v2-testV2
      app-service: backend-ecs-service-v2-testV2
      app-cluster: marketplace-ecs-cluster-test
      deploy_env: test
