name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  ci_other_file:
    uses: camistyles/infra_test/.github/workflows/build-node.yml@main
    with:
      codeCoverage: "50"
