name: Deploy staging env

on: 
  push:
    branches:
      - "releases/**"
  create:
    branches:
      - "releases/**"
jobs:
  ci:
    uses: ./.github/workflows/build-node.yml
    with:
      codeCoverage: "50"

  ci-cd-image:
    uses: ./.github/workflows/image-tmp.yml
    needs: ci
    with:
      region: "us-east-2"
      repo: "enigma_backend"
      deploy_env: "staging"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    uses: ./.github/workflows/deploy-tmp.yml
    needs:
      - ci
      - ci-cd-image
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      image: ${{ needs.ci-cd-image.outputs.built-image }}
      task-definition: backend-ecs-task-v2-stagingV2
      container-name: backend-container-v2-stagingV2
      app-service: backend-ecs-service-v2-stagingV2
      app-cluster: marketplace-ecs-cluster-stage
      deploy_env: staging

