name: Deploy production env

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:
    
jobs:
  ci-other-file:
    uses: camistyles/infra_test/.github/workflows/build-node.yml@4fe3f97039322f88d0d0e64d1cca33f69eafc4bc
    with:
      codeCoverage: "50"
